    friends = mysql.query_db('SELECT * FROM friend;')  # call the query_db function, pass in the query as a string

Running Query: SELECT * FROM friend;
Something went wrong (1146, "Table 'first_flask.friend' doesn't exist")
False
127.0.0.1 - - [22/Jul/2019 11:46:37] "GET / HTTP/1.1" 200 -

————

Running Query: SELECT * FROM friends WHERE ("id"=1)
Something went wrong (0, '')

————

Running Query: SELECT * FROM friends WHERE ("id"=1)
Something went wrong (0, '')
127.0.0.1 - - [22/Jul/2019 11:49:33] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/blacroix/Desktop/CodingDojo/python/flask_mysql/first_flask_mysql/server.py", line 8, in index
    friends = mysql.query_db('SELECT * FROM friends WHERE ("id"=1)')  # call the query_db function, pass in the query as a string
  File "/Users/blacroix/Desktop/CodingDojo/python/flask_mysql/first_flask_mysql/mysqlconnection.py", line 40, in query_db
    self.connection.close()
  File "/Users/blacroix/Desktop/CodingDojo/python/python/my_environments/py3env/lib/python3.7/site-packages/pymysql/connections.py", line 354, in close
    raise err.Error("Already closed")
